#!/bin/bash
echo "Running post-merge hook..."
docker compose -f /opt/bonbon_kids/docker-compose.yml restart app
sleep 5
docker compose -f /opt/bonbon_kids/docker-compose.yml exec -T app php artisan responsecache:clear
docker compose -f /opt/bonbon_kids/docker-compose.yml exec -T app php warmup.php
